name = "spectrum"
author = "DecentM"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d22e6a2665ae1b4039e080d854336b45be73118d6b4a693c309a84d230ed6ee"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"

[options]
datapack-folder = "datapacks"
